### ISSUE TITLE
Unhandled Rejection:

### ISSUE THREAD

**Issue by Setman590** [mr-guard/dayz-server-manager#111]
Should I worry about this error?

Unhandled Rejection: TypeError: Cannot read properties of undefined (reading '0')
    at C:\snapshot\dayz-server-manager\dist\services\events.js:77:81
    at Events.<anonymous> (C:\snapshot\dayz-server-manager\dist\services\events.js:50:39)
    at Generator.next (<anonymous>)
    at C:\snapshot\dayz-server-manager\dist\services\events.js:17:71
    at new Promise (<anonymous>)
    at C:\snapshot\dayz-server-manager\dist\services\events.js:13:12
    at runTask (C:\snapshot\dayz-server-manager\dist\services\events.js:48:43)
    at Events.<anonymous> (C:\snapshot\dayz-server-manager\dist\services\events.js:61:26)
    at Generator.next (<anonymous>)
    at C:\snapshot\dayz-server-manager\dist\services\events.js:17:71

**Comment by mr-guard** [comment]
You have created a RCON message event without the message param

**Comment by Setman590** [comment]
Seams to be working with the new version.

**Comment by mr-guard** [comment]
Great, closing this as resolved then
