### ISSUE TITLE
Error after last DSM update

### ISSUE THREAD

**Issue by DayzNoName** [mr-guard/dayz-server-manager#122]
![image](https://github.com/mr-guard/dayz-server-manager/assets/117022289/79f37c77-6f26-4fbc-836c-c2db8ebec5f6)

**Comment by itzeddie** [comment]
Also getting this error on my local test server. I've tried utilising a new SteamCMD folder to no avail.

**Comment by mr-guard** [comment]
IDK about this error.
Has to do something with corruption of server or steamcmd files

Try to delete the server folder to get the manager to reinstall it
If it doesn't help try the same thing with the streamcmd folder and the workshop folder

Unfortunately there is nothing the server manager can do about this

**Comment by jilabaca** [comment]
I have the same problem with a new installation, any ideas?

`bash 
@2024-05-08T19:28:55.005Z | INFO      | SteamCMD     | Server Update Progress: downloading: 72.62%
@2024-05-08T19:28:57.021Z | INFO      | SteamCMD     | Server Update Progress: downloading: 75.49%
@2024-05-08T19:28:59.013Z | INFO      | SteamCMD     | Server Update Progress: downloading: 77.09%
@2024-05-08T19:29:01.007Z | INFO      | SteamCMD     | Server Update Progress: downloading: 78.63%
@2024-05-08T19:29:03.026Z | INFO      | SteamCMD     | Server Update Progress: downloading: 79.79%
@2024-05-08T19:29:05.019Z | INFO      | SteamCMD     | Server Update Progress: downloading: 80.92%
@2024-05-08T19:29:07.011Z | INFO      | SteamCMD     | Server Update Progress: downloading: 82.44%
@2024-05-08T19:29:09.007Z | INFO      | SteamCMD     | Server Update Progress: downloading: 84.13%
@2024-05-08T19:29:11.027Z | INFO      | SteamCMD     | Server Update Progress: downloading: 91.22%
@2024-05-08T19:29:13.022Z | INFO      | SteamCMD     | Server Update Progress: downloading: 97.70%
@2024-05-08T19:29:15.009Z | INFO      | SteamCMD     | Server Update Progress: downloading: 98.78%
@2024-05-08T19:29:17.022Z | INFO      | SteamCMD     | Server Update Progress: downloading: 99.96%
@2024-05-08T19:29:19.011Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 22.58%
@2024-05-08T19:29:21.025Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 47.11%
@2024-05-08T19:29:23.017Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 70.99%
@2024-05-08T19:29:25.006Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 95.53%
@2024-05-08T19:29:26.038Z | WARN      | Discord      | Queueing message because client did not start or is not yet ready [ false ]
@2024-05-08T19:29:26.040Z | ERROR     | Bootstrap    | Setup failed: Server installation failed [
  Error: Server installation failed
      at ManagerController.<anonymous> (/snapshot/dayz-server-manager/dist/control/manager-controller.js:215:27)
      at Generator.next (<anonymous>)
      at fulfilled (/snapshot/dayz-server-manager/dist/control/manager-controller.js:14:58)
]
dayz@srv:~$
`

**Comment by 1Example** [comment]
Hey, at line 160 the parameter "serverExe" should be replaced from "DayZServer_x64.exe" to "DayZServer_x64"
