### ISSUE TITLE
There was an error when following the tutorial to build it

### ISSUE THREAD

**Issue by neeko8** [mr-guard/dayz-server-manager#152]
Error: Server installation failed
      at ManagerController.<anonymous> (/snapshot/dayz-server-manager/dist/control/manager-controller.js:215:27)
      at Generator.next (<anonymous>)
      at fulfilled (/snapshot/dayz-server-manager/dist/control/manager-controller.js:14:58)

I'm using a steam account that doesn't have a dayz game in it, do I have to use an account that has the game to set up the server?

**Comment by jonni111** [comment]
Да
