### ISSUE TITLE
Missing file permissions

### ISSUE THREAD

**Issue by Weedefix** [mr-guard/dayz-server-manager#154]
Hi

installing as described [here](https://github.com/mr-guard/dayz-server-manager?tab=readme-ov-file#linux-server)
Using Ubuntu Server 24.04, everything freshly installed and up2date. (update, upgrade, dist-upgrade).
Added a user "dayz", gave permissions to user and folder (777 for testing). Installing gives error code as seen below. Installing as root does not work too. Cannot find information on how to fix this. Seems like steamcmd can not access certain files/folders.

Any suggestions?

Thanks & cheers
Soki

root@server /dayz # ./dayz-server-manager
@2024-08-13T16:32:29.819Z | IMPORTANT | Manager      | Starting DZSM Version: 3.10.0
@2024-08-13T16:32:29.820Z | INFO      | Database     | Database Setup: node 16.16.0 : v93-linux-x64
@2024-08-13T16:32:29.822Z | IMPORTANT | Config       | Trying to read config at: /dayz/server-manager.json
@2024-08-13T16:32:29.826Z | IMPORTANT | Config       | Successfully read config
@2024-08-13T16:32:29.953Z | IMPORTANT | Bootstrap    | Initially checking SteamCMD, Server Installation and Mods. Please wait. This may take some minutes...
@2024-08-13T16:32:29.953Z | IMPORTANT | SteamCMD     | Checking/Installing SteamCMD
@2024-08-13T16:32:29.973Z | INFO      | SteamCMD     | Progress:   0% - Checking for available updates...
@2024-08-13T16:32:30.725Z | INFO      | SteamCMD     | Progress: ---- - Verifying installation...
@2024-08-13T16:32:31.518Z | IMPORTANT | SteamCMD     | Updating DayZ Server using app id: 223350, validating: false
@2024-08-13T16:32:40.410Z | ERROR     | SteamCMD     | SteamCMD "+force_install_dir /dayz/DayZServer +login myuserhere ****** +app_update 223350 +quit" failed [
  {
    status: 8,
    stdout: "Redirecting stderr to '/root/Steam/logs/stderr.txt'\n" +
      "Logging directory: '/root/Steam/logs'[  0%] Checking for available updates...[----] Verifying installation...UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1721172922\n" +
      "-- type 'quit' to exit --Loading Steam API...Process 3665 failed to shm_open /u0-ValveIPCSharedObj-SteamOKLogging in user 'dh74ooueqy' to Steam Public...OKWaiting for client config...OK\n" +
      "Waiting for user info...OKERROR! Failed to install app '223350' **(Missing file permissions)**",
    stderr: ''
  }
]
@2024-08-13T16:32:40.416Z | WARN      | Discord      | Queueing message because client did not start or is not yet ready [ false ]
@2024-08-13T16:32:40.417Z | ERROR     | SteamCMD     | Failed to update server
@2024-08-13T16:32:40.417Z | ERROR     | Bootstrap    | Setup failed: Server installation failed [
  Error: Server installation failed
      at ManagerController.<anonymous> (/snapshot/dayz-server-manager/dist/control/manager-controller.js:215:27)
      at Generator.next (<anonymous>)
      at fulfilled (/snapshot/dayz-server-manager/dist/control/manager-controller.js:14:58)
]

**Comment by rklxmok** [comment]
Do not run this program as root. Only as the dayz user and it will fix the issue. 

Also if you want to correct file acl's per file system change, run this as root/sudo after changes

`chmod -R 777 /dayz && chown -R dayz:dayz /dayz && setfacl -m g:users:rwx -R /dayz && setfacl -m g:<your users group name here>:rwx -R /dayz && setfacl -m g:dayz:rwx -R /dayz`
