### ISSUE TITLE
install failures  - ubuntu 24.04

### ISSUE THREAD

**Issue by vaxoiva** [mr-guard/dayz-server-manager#163]
`dayz@vm661mqpr:~$ ./dayz-server-manager
@2024-11-03T11:34:48.789Z | IMPORTANT | Manager      | Starting DZSM Version: 3.10.0
@2024-11-03T11:34:48.792Z | INFO      | Database     | Database Setup: node 16.16.0 : v93-linux-x64
@2024-11-03T11:34:48.796Z | IMPORTANT | Config       | Trying to read config at: /dayz/server-manager.json
@2024-11-03T11:34:48.813Z | IMPORTANT | Config       | Successfully read config
@2024-11-03T11:34:48.997Z | IMPORTANT | Bootstrap    | Initially checking SteamCMD, Server Installation and Mods. Please wait. This may take some minutes...
@2024-11-03T11:34:49.156Z | IMPORTANT | SteamCMD     | Download of SteamCMD done
@2024-11-03T11:34:49.271Z | IMPORTANT | SteamCMD     | Extraction of SteamCMD done
@2024-11-03T11:34:54.279Z | IMPORTANT | SteamCMD     | Checking/Installing SteamCMD
@2024-11-03T11:34:54.314Z | INFO      | SteamCMD     | Progress:   0% - Checking for available update...
@2024-11-03T11:34:54.827Z | INFO      | SteamCMD     | Progress: ---- - Downloading update (0 of 48914 KB)...
@2024-11-03T11:34:55.077Z | INFO      | SteamCMD     | Progress:   0% - Downloading update (0 of 48914 KB)...
@2024-11-03T11:34:55.329Z | INFO      | SteamCMD     | Progress:   0% - Downloading update (4649 of 48914 KB)...
@2024-11-03T11:34:55.597Z | INFO      | SteamCMD     | Progress:   9% - Downloading update (9072 of 48914 KB)...
@2024-11-03T11:34:55.847Z | INFO      | SteamCMD     | Progress:  18% - Downloading update (13326 of 48914 KB)...
@2024-11-03T11:34:56.098Z | INFO      | SteamCMD     | Progress:  27% - Downloading update (17192 of 48914 KB)...
@2024-11-03T11:34:56.348Z | INFO      | SteamCMD     | Progress:  35% - Downloading update (21125 of 48914 KB)...
@2024-11-03T11:34:56.598Z | INFO      | SteamCMD     | Progress:  43% - Downloading update (25086 of 48914 KB)...
@2024-11-03T11:34:56.848Z | INFO      | SteamCMD     | Progress:  51% - Downloading update (28963 of 48914 KB)...
@2024-11-03T11:34:57.098Z | INFO      | SteamCMD     | Progress:  59% - Downloading update (32851 of 48914 KB)...
@2024-11-03T11:34:57.349Z | INFO      | SteamCMD     | Progress:  67% - Downloading update (36751 of 48914 KB)...
@2024-11-03T11:34:57.599Z | INFO      | SteamCMD     | Progress:  75% - Downloading update (40454 of 48914 KB)...
@2024-11-03T11:34:57.971Z | INFO      | SteamCMD     | Progress:  82% - Downloading update (43458 of 48914 KB)...
@2024-11-03T11:34:58.220Z | INFO      | SteamCMD     | Progress:  88% - Downloading update (45711 of 48914 KB)...
@2024-11-03T11:34:58.471Z | INFO      | SteamCMD     | Progress:  93% - Downloading update (47687 of 48914 KB)...
@2024-11-03T11:34:58.839Z | INFO      | SteamCMD     | Progress:  97% - Downloading update (48914 of 48914 KB)...
@2024-11-03T11:34:58.840Z | INFO      | SteamCMD     | Progress: ---- - Applying update...
@2024-11-03T11:34:58.884Z | INFO      | SteamCMD     | Progress: ---- - Extracting package...
@2024-11-03T11:35:02.205Z | INFO      | SteamCMD     | Progress: ---- - Installing update...
@2024-11-03T11:35:02.211Z | INFO      | SteamCMD     | Progress: ---- - Cleaning up...
@2024-11-03T11:35:02.212Z | INFO      | SteamCMD     | Progress: ---- - Update complete, launching...
@2024-11-03T11:35:02.405Z | INFO      | SteamCMD     | Progress:   0% - Checking for available updates...
@2024-11-03T11:35:02.906Z | INFO      | SteamCMD     | Progress: ---- - Verifying installation...
@2024-11-03T11:35:02.907Z | INFO      | SteamCMD     | Progress:   0% - Checking for available updates...
@2024-11-03T11:35:03.157Z | INFO      | SteamCMD     | Progress: ---- - Download complete.
@2024-11-03T11:35:03.197Z | INFO      | SteamCMD     | Progress: ---- - Extracting package...
@2024-11-03T11:35:06.076Z | INFO      | SteamCMD     | Progress: ---- - Installing update...
@2024-11-03T11:35:06.124Z | INFO      | SteamCMD     | Progress: ---- - Cleaning up...
@2024-11-03T11:35:06.125Z | INFO      | SteamCMD     | Progress: ---- - Update complete, launching Steamcmd...
@2024-11-03T11:35:06.327Z | INFO      | SteamCMD     | Progress:   0% - Checking for available updates...
@2024-11-03T11:35:06.828Z | INFO      | SteamCMD     | Progress: ---- - Verifying installation...
@2024-11-03T11:35:07.539Z | IMPORTANT | SteamCMD     | Updating DayZ Server using app id: 223350, validating: false
@2024-11-03T11:35:16.794Z | INFO      | SteamCMD     | Server Update Progress: reconfiguring: 0.00%
@2024-11-03T11:35:18.014Z | INFO      | SteamCMD     | Server Update Progress: reconfiguring: 0.00%
@2024-11-03T11:35:20.006Z | INFO      | SteamCMD     | Server Update Progress: downloading: 1.39%
@2024-11-03T11:35:22.013Z | INFO      | SteamCMD     | Server Update Progress: downloading: 5.84%
@2024-11-03T11:35:24.015Z | INFO      | SteamCMD     | Server Update Progress: downloading: 9.65%
@2024-11-03T11:35:26.003Z | INFO      | SteamCMD     | Server Update Progress: downloading: 13.60%
@2024-11-03T11:35:28.026Z | INFO      | SteamCMD     | Server Update Progress: downloading: 17.00%
@2024-11-03T11:35:30.015Z | INFO      | SteamCMD     | Server Update Progress: downloading: 20.63%
@2024-11-03T11:35:32.015Z | INFO      | SteamCMD     | Server Update Progress: downloading: 23.34%
@2024-11-03T11:35:34.010Z | INFO      | SteamCMD     | Server Update Progress: downloading: 26.34%
@2024-11-03T11:35:36.015Z | INFO      | SteamCMD     | Server Update Progress: downloading: 29.17%
@2024-11-03T11:35:38.044Z | INFO      | SteamCMD     | Server Update Progress: downloading: 32.67%
@2024-11-03T11:35:40.018Z | INFO      | SteamCMD     | Server Update Progress: downloading: 38.02%
@2024-11-03T11:35:42.029Z | INFO      | SteamCMD     | Server Update Progress: downloading: 43.77%
@2024-11-03T11:35:44.011Z | INFO      | SteamCMD     | Server Update Progress: downloading: 48.23%
@2024-11-03T11:35:46.018Z | INFO      | SteamCMD     | Server Update Progress: downloading: 51.78%
@2024-11-03T11:35:48.028Z | INFO      | SteamCMD     | Server Update Progress: downloading: 55.12%
@2024-11-03T11:35:50.011Z | INFO      | SteamCMD     | Server Update Progress: downloading: 59.66%
@2024-11-03T11:35:52.023Z | INFO      | SteamCMD     | Server Update Progress: downloading: 63.28%
@2024-11-03T11:35:54.018Z | INFO      | SteamCMD     | Server Update Progress: downloading: 66.13%
@2024-11-03T11:35:56.017Z | INFO      | SteamCMD     | Server Update Progress: downloading: 68.39%
@2024-11-03T11:35:58.025Z | INFO      | SteamCMD     | Server Update Progress: downloading: 70.11%
@2024-11-03T11:36:00.024Z | INFO      | SteamCMD     | Server Update Progress: downloading: 72.52%
@2024-11-03T11:36:02.024Z | INFO      | SteamCMD     | Server Update Progress: downloading: 75.44%
@2024-11-03T11:36:04.015Z | INFO      | SteamCMD     | Server Update Progress: downloading: 78.22%
@2024-11-03T11:36:06.023Z | INFO      | SteamCMD     | Server Update Progress: downloading: 82.23%
@2024-11-03T11:36:08.005Z | INFO      | SteamCMD     | Server Update Progress: downloading: 86.92%
@2024-11-03T11:36:10.026Z | INFO      | SteamCMD     | Server Update Progress: downloading: 91.24%
@2024-11-03T11:36:12.038Z | INFO      | SteamCMD     | Server Update Progress: downloading: 96.13%
@2024-11-03T11:36:14.019Z | INFO      | SteamCMD     | Server Update Progress: downloading: 100.00%
@2024-11-03T11:36:16.025Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 8.18%
@2024-11-03T11:36:18.008Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 23.41%
@2024-11-03T11:36:20.015Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 38.95%
@2024-11-03T11:36:22.004Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 50.35%
@2024-11-03T11:36:24.011Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 64.45%
@2024-11-03T11:36:26.026Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 80.49%
@2024-11-03T11:36:28.012Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 93.97%
@2024-11-03T11:36:29.624Z | WARN      | Discord      | Queueing message because client did not start or is not yet ready [ false ]
@2024-11-03T11:36:29.627Z | ERROR     | Bootstrap    | Setup failed: Server installation failed [
  Error: Server installation failed
      at ManagerController.<anonymous> (/snapshot/dayz-server-manager/dist/control/manager-controller.js:215:27)
      at Generator.next (<anonymous>)
      at fulfilled (/snapshot/dayz-server-manager/dist/control/manager-controller.js:14:58)
`

**Comment by yuv41** [comment]
have you managed to fix this?

**Comment by yuv41** [comment]
> nope

damn. trying this on my debian 12 machine and its throwing this issue, even in debug more there is no more info

**Comment by vvrasnikov** [comment]
set "serverExe" to "DayZServer"

**Comment by rklxmok** [comment]
Are you running the server manager as root/sudo?

**Comment by Kr3jzolPL** [comment]
> set "serverExe" to "DayZServer"

Thanks man i was trying to setup server in truenas scale using docker and custom app page after weeks of searching it was last puzzle thanks man again
