### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by fr1nk** [mr-guard/dayz-server-manager#23]
Hi, started getting this error today, am not sure if it's a steam issue or something related to the server manager:

```
@2022-02-01T03:48:37.529Z | IMPORTANT | Manager    | Starting DZSM Version: 2.1.1
@2022-02-01T03:48:37.530Z | IMPORTANT | Config     | Trying to read config at: C:\Servers\DayZSADeerIsle\server-manager.json
@2022-02-01T03:48:37.539Z | IMPORTANT | Config     | Successfully read config
@2022-02-01T03:48:37.540Z | INFO      | Database   | Database Setup: node 14.17.0 : v83-win32-x64
@2022-02-01T03:48:37.788Z | IMPORTANT | Manager    | Initially checking SteamCMD, Server Installation and Mods. Please wait. This may take some minutes...
@2022-02-01T03:48:37.788Z | IMPORTANT | SteamCMD   | Checking/Installing SteamCMD
Redirecting stderr to 'C:\Servers\DayZSADeerIsle\SteamCMD\logs\stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1642451655
-- type 'quit' to exit --
Loading Steam API...OK


Redirecting stderr to 'C:\Servers\DayZSADeerIsle\SteamCMD\logs\stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1642451655
-- type 'quit' to exit --
Loading Steam API...OK
Logging in user 'Andymantium' to Steam Public...FAILED (Rate Limit Exceeded)


@2022-02-01T03:48:40.644Z | ERROR     | SteamCMD   | SteamCMD "+login MyUserID ****** +force_install_dir C:\Servers\DayZSADeerIsle\DayZServer +app_update 223350 validate +quit" failed [ { status: 5, stdout: '', stderr: '' } ]
@2022-02-01T03:48:40.646Z | ERROR     | SteamCMD   | Failed to update server
@2022-02-01T03:48:40.646Z | ERROR     | Manager    | Server installation failed [
  Error: Server installation failed
      at ManagerController.<anonymous> (C:\snapshot\dayz-server-manager\dist\control\manager-controller.js:168:35)
      at Generator.next (<anonymous>)
      at fulfilled (C:\snapshot\dayz-server-manager\dist\control\manager-controller.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
]
Press any key to continue . . .
```

Thanks

**Comment by mr-guard** [comment]
This happens because SteamCMD has a rate limit
It is triggered if you try to download too many mods in short period of time (maybe restarting the server multiple times?)

If the mods are up to date, you can work around this by setting "updateModsBeforeServerStart" to false in the manager config
you must manually trigger mod updates if they are required

**Comment by mr-guard** [comment]
See #48
