### ISSUE TITLE
Steam mods not found

### ISSUE THREAD

**Issue by markusa380** [mr-guard/dayz-server-manager#80]
<img width="738" alt="Screenshot 2023-11-19 202332" src="https://github.com/mr-guard/dayz-server-manager/assets/5033990/45a37ffa-7a5a-468c-9080-55de4052a97c">

Not sure what I did wrong. It's CF and VPPAdminTools.

**Comment by radixtenshi** [comment]
It's probably because you're not logged in with a user. It says anonymous there.

trata de iniciar sesion en steamcmd con tu usuario antes de ejecutar el server manager. Es decir ejecuta la consola CMD de steamCDM (steamcmd.exe). Luego usa el comando: login <username> [<password>] [<Steam guard code>]

Once logged in, steamCMD saves your credentials in Chache. Close steamcmd then. 

Now if you open the server manager to update the mods must work.

it's also recommended that you delete all the contents of the Workshop folder.

If you can't solve the problem you can send me a message and I'll see how I can help you.

See ya

**Comment by markusa380** [comment]
Okay, so I found out that the problem was that the steam account I used did not own DayZ.
Now, that has been mentioned in the documentation, but I suggest adding something like this under the _Adding workshop mods_  heading:

_This is only possible if logged in with a user and the user owns DayZ_.

Also, this is definitely a very unfortunate limitation. Games like CS:GO or CS:2 require the Steam Authenticator to be fully usable, so the option is to either disable Authenticator and loose access to marketplace in those games or essentially buy DayZ a second time for the server user.

**Comment by dm5xx** [comment]
Same here - and i am using an account with dayz in it.

It was working befor with an account without the dayz on it. this seems to stopped working. but also no luck with may accoutn everythign set up...

@2023-11-21T17:48:19.062Z | INFO      | SteamCMD     | Progress: ---- - Installation wird überprüft …
@2023-11-21T17:48:30.082Z | IMPORTANT | SteamCMD     | STEAM GUARD DETECTED!
@2023-11-21T17:48:30.082Z | IMPORTANT | SteamCMD     |
@2023-11-21T17:48:30.082Z | IMPORTANT | SteamCMD     | It is recommended to create a separate steam account with copy of DayZ and have SteamGuard set to Email-Code or Deactivated (Mobile Authenticator Code needs to be entered EVERY TIME, Email Code is saved)
@2023-11-21T17:48:30.083Z | IMPORTANT | SteamCMD     | Otherwise the server manager might get stuck when doing updates until you enter the code
Enter your Steam Guard code:
93PVR
OK

@2023-11-21T17:52:15.481Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 0.00%
@2023-11-21T17:52:21.270Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 23.48%
@2023-11-21T17:52:23.029Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 31.99%
@2023-11-21T17:52:25.020Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 41.38%
@2023-11-21T17:52:27.031Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 50.93%
@2023-11-21T17:52:29.022Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 59.19%
@2023-11-21T17:52:31.021Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 68.08%
@2023-11-21T17:52:33.027Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 78.33%
@2023-11-21T17:52:35.023Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 87.73%
@2023-11-21T17:52:37.030Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 95.77%
@2023-11-21T17:52:38.584Z | ERROR     | SteamCMD     | Mod 1559212036 was not found
@2023-11-21T17:52:47.912Z | INFO      | SteamCMD     | Downloading mod: 2572331007




@2023-11-21T17:54:28.809Z | INFO      | SteamCMD     | Downloading mod: 2793893086
@2023-11-21T17:54:44.220Z | INFO      | SteamCMD     | Downloading mod: 2792982069
@2023-11-21T17:55:03.659Z | ERROR     | SteamCMD     | Failed to update mods: 2792982069,2545327648,1564026768,1559212036,2430317812
@2023-11-21T17:55:03.678Z | ERROR     | Bootstrap    | Setup failed: Updating Mods failed [
  Error: Updating Mods failed
      at ManagerController.<anonymous> (C:\snapshot\dayz-server-manager\dist\control\manager-controller.js:203:27)
      at Generator.next (<anonymous>)
      at fulfilled (C:\snapshot\dayz-server-manager\dist\control\manager-controller.js:14:58)
]
Drücken Sie eine beliebige Taste . . .

**Comment by dm5xx** [comment]
i have for sure a valid dayz in my steam account who is running the update. at it seem that everxything is fine in the folder: E:\dayzserver-manager\Workshop\steamapps\workshop\content\221100 => all mods in the config file are downloaded and visible...

**Comment by radixtenshi** [comment]
i told you before. delete the workshop folder. could be a local file problem. dont matter if the folder have mods inside. just delete it and let the manager download all again

**Comment by dm5xx** [comment]
i am someone different - i deleted everything, just starting with .exe and ..manager.json from scratch... :)

**Comment by mr-guard** [comment]
@radixtenshi thx for helping out and @markusa380 glad you got it fixed

I would add the info to that place as well, but then it would still be missing in 10 other places depending on what people may read or not read^^

Anyway, the proper solution would be to detect the error case in the client and print a descriptive error message

**Comment by peschelnet** [comment]
I'm having this same exact issue as @markusa380 where mods fail to download along with another side issue (The WebUI doesn't load/connect)

Here is exactly what I've done.

1. Delete the Workshop Folder
2. Login to SteamCMD using the Steam account you recommended I create for the server.
3. Close the SteamCMD widow
4. Start the dayz-server-manager application

The server loads to the point of getting to the Mods and then crashes (the exact same error as @markusa380 ). I did notice that it says I'm logged in as Anonymous and not my account name.

----
As a side note, the WebUI doesn't load or isn't accessible when I put in _<serveripaddress>_:2313

The server firewall is turned off for testing and the port 2313 is open.

I can open another thread if that would be better.

Thank for your help.
