### ISSUE TITLE
I found maybe some Bugs

### ISSUE THREAD

**Issue by BastyJuice** [mr-guard/dayz-server-manager#86]
Hello,

i found some bugs i think.

1. The Time seems to Assyncron to Systemtime and DayZ Server in DayZServer
![Timeasyncron](https://github.com/mr-guard/dayz-server-manager/assets/13349817/34bdd824-4160-4096-aa4b-7cca36a1a0b4)

2. Restart Button und Maintenance seems not Working only Force Variant.

3. The Hook "afterStart" ist not Working

4. When the Server exe got something wrong in the config it place the logfiles in the root not in \server-manager-logs

> 1 File called manager-exception-dump-1703865438216.log with:
> Unhandled exception - TypeError: Cannot read properties of undefined (reading 'guilds')

> 2 Filled called manager-exit-dump-1703858863069.log with:
> Unplanned exit - 1 - Error
>     at process.exit (C:\snapshot\dayz-server-manager\dist\util\exit-capture.js:10:101)
>     at process.<anonymous> (C:\snapshot\dayz-server-manager\dist\index.js:25:17)
>     at process.emit (node:events:527:28)
>     at process._fatalException (node:internal/process/execution:167:25)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

6. Pressing F5 will Logout User instead of Refreshing the Site

7. Server CMD Suggest to do the LOgging Fix but i have done it already :-)

8. Is not a Bug more a Request Playlist should have Buttons to Add these Players to White or Banlist :-)

**Comment by BastyJuice** [comment]
sorry for Point 4: saw to late that afterStart does not exit as Hook :-) maybee you cann add it...

**Comment by BastyJuice** [comment]
also the add mode button on discord channels does not work had to do this in config after that the buttion seems to work

**Comment by BastyJuice** [comment]
sometimes i get Discord error

Unhandled Exception: TypeError: Cannot read properties of undefined (reading 'guilds')
    at DiscordBot.onReady (C:\snapshot\dayz-server-manager\dist\services\discord.js:86:70)
    at Client.<anonymous> (C:\snapshot\dayz-server-manager\dist\services\discord.js:58:26)
    at Client.emit (node:events:527:28)
    at WebSocketManager.triggerClientReady (C:\snapshot\dayz-server-manager\node_modules\discord.js\src\client\websocket\WebSocketManager.js:379:17)
    at WebSocketManager.checkShardsReady (C:\snapshot\dayz-server-manager\node_modules\discord.js\src\client\websocket\WebSocketManager.js:362:10)
    at WebSocketShard.<anonymous> (C:\snapshot\dayz-server-manager\node_modules\discord.js\src\client\websocket\WebSocketManager.js:189:14)
    at WebSocketShard.emit (node:events:527:28)
    at WebSocketShard.checkReady (C:\snapshot\dayz-server-manager\node_modules\discord.js\src\client\websocket\WebSocketShard.js:524:12)
    at WebSocketShard.onPacket (C:\snapshot\dayz-server-manager\node_modules\discord.js\src\client\websocket\WebSocketShard.js:496:16)
    at WebSocketShard.onMessage (C:\snapshot\dayz-server-manager\node_modules\discord.js\src\client\websocket\WebSocketShard.js:327:10)
Unplanned exit
Trace
    at process.exit (C:\snapshot\dayz-server-manager\dist\util\exit-capture.js:9:13)
    at process.<anonymous> (C:\snapshot\dayz-server-manager\dist\index.js:25:17)
    at process.emit (node:events:527:28)
    at process._fatalException (node:internal/process/execution:167:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by mr-guard** [comment]
Hi, thanks for the report

1. the servermanager show its time in UTC (as indicated by the trailing Z). Currently this cannot be changed
2. The non force variants rely on RCON to be working, can you double check that RCON is configured and connected?
3. Might be added in the future
4/5. error captures are dumped that to make them more visisble
6. Tick "remember me" in the login screen
7. You can safely ignore that. Detecting this properly involves reading the windows registry which is messy
8. Might be added in the future as well :)
