### ISSUE TITLE
Random fatalException of Server Manager

### ISSUE THREAD

**Issue by bruunooh** [mr-guard/dayz-server-manager#97]
Hi, 

i feel bad to bother you again but the manager is crashing somehow randomly.
The console shows this message:

```
Unplanned exit - 1 - Error
    at process.exit (C:\snapshot\dayz-server-manager\dist\util\exit-capture.js:10:101)
    at process.<anonymous> (C:\snapshot\dayz-server-manager\dist\index.js:25:17)
    at process.emit (node:events:527:28)
    at process._fatalException (node:internal/process/execution:167:25)
```

I've added events before this problem occured. i have removed already a part of it (Locking the server caused some error messages) but it doesn't fix it.

that's the remaining events: 

```
    "events": [
      {
          "name": "Restart every 4 hours",
          "type": "restart",
          "cron": "0 0,4,8,12,16,20 * * *"
      },
      {
          "name": "Restart Notification (30m)",
          "type": "message",
          "cron": "30 3,7,11,15,19,23 * * *",
          "content": [
            "Neustart in 30 Minuten. Bitte in Sicherheit bringen."
          ]
      },
      {
          "name": "Restart Notification (15m)",
          "type": "message",
          "cron": "45 3,7,11,15,19,23 * * *",
          "content": [
            "Neustart in 15 Minuten. Bitte in Sicherheit bringen."
          ]
      },
      {
          "name": "Restart Notification (5m)",
          "type": "message",
          "cron": "55 3,7,11,15,19,23 * * *",
          "content": [
            "Neustart in 5 Minuten. Server wird gesperrt. Kick erfolgt in 4 Minuten!"
          ]
      },
      {
          "name": "Restart / Kick Notification (2m)",
          "type": "message",
          "cron": "58 3,7,11,15,19,23 * * *",
          "content": [
            "Neustart in 2 Minuten. Verbleibende Spieler werden in 60 Sekunden entfernt!"
          ]
      },
      {
          "name": "Restart Kick (1m)",
          "type": "kickAll",
          "cron": "59 3,7,11,15,19,23 * * *"
      }
    ],
```

Anyone have an idea?

**Comment by mr-guard** [comment]
If you dont mind, please join the discord and send me your full server manager logs.
Dont post them here, they could contain sensitive information.

"Unplanned exit" usually means, that a library or dependency caused the program to exit.

**Comment by mr-guard** [comment]
Its in the readme, click the chat button

**Comment by mr-guard** [comment]
@bruunooh 
Found the issue:
```
{
          "name": "Restart / Kick Notification (2m)",
          "type": "message",
          "cron": "58 3,7,11,15,19,23 * * *",
          "content": [
            "Neustart in 2 Minuten. Verbleibende Spieler werden in 60 Sekunden entfernt!"
          ]
      },
```

replace `"content": [` with `"params": [`
